"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { DndContext, DragOverlay, PointerSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent, type DragStartEvent } from "@dnd-kit/core";
import { ChevronLeft, ChevronRight, Clock, GripVertical, Lightbulb, MapPin, Plus, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DayJourneyView } from "@/components/views/DayJourneyView";
import { dateParts, formatTripDate, monthGrid } from "@/lib/date-utils";
import { useTravelStore } from "@/store/use-travel-store";
import { api } from "@/lib/api-client";
import type { TravelObject, Trip } from "@/types/travel";

type Mode = "month" | "week" | "day";
const defaultColors: Record<string, string> = { unclassified: "#64748b", flight: "#0ea5e9", hotel: "#8b5cf6", food: "#f97316", commute: "#f59e0b", activity: "#10b981", sightseeing: "#f43f5e" };
const palette = ["#14b8a6", "#3b82f6", "#a855f7", "#ec4899", "#f97316", "#84cc16", "#64748b"];
function typeColor(type: string, colors: Record<string, string>) { return colors[type] ?? defaultColors[type] ?? palette[[...type].reduce((sum, char) => sum + char.charCodeAt(0), 0) % palette.length]; }
function shiftDate(date: string, days: number) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }
function sundayOf(date: string) { const value = new Date(`${date}T00:00:00Z`); return shiftDate(date, -value.getUTCDay()); }
function selectionRing(selected: boolean, primary: boolean) { return selected ? primary ? "ring-2 ring-white ring-offset-2 ring-offset-emerald-600" : "ring-2 ring-emerald-600" : ""; }
function itemDates(item: TravelObject, timezone: string) { const first = item.date?.slice(0, 10) ?? (item.startDateTime ? dateParts(item.startDateTime, timezone).date : null); const last = item.endDate?.slice(0, 10) ?? (item.endDateTime ? dateParts(item.endDateTime, timezone).date : first); return { first, last }; }
function itemAppearsOnDate(item: TravelObject, date: string, timezone: string) { const { first, last } = itemDates(item, timezone); return Boolean(first && first <= date && (last ?? first) >= date); }
function agendaSort(a: TravelObject, b: TravelObject) { return (a.dayOrder ?? Number.MAX_SAFE_INTEGER) - (b.dayOrder ?? Number.MAX_SAFE_INTEGER) || (a.startTime ?? "99:99").localeCompare(b.startTime ?? "99:99") || a.createdAt.localeCompare(b.createdAt); }

function CalendarDragPreview({ items, timezone, typeColors }: { items: TravelObject[]; timezone: string; typeColors: Record<string, string> }) {
  return <div className="w-64 space-y-1.5">{items.map((item) => <article key={item.id} className="rounded-lg border border-l-4 bg-background px-3 py-2 text-xs shadow-xl" style={{ borderLeftColor: typeColor(item.type, typeColors) }}><p className="truncate font-semibold">{item.title}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{item.startDateTime ? formatTripDate(item.startDateTime, timezone, { month: "short", day: "numeric", ...(item.isAllDay ? {} : { hour: "numeric", minute: "2-digit" }) }) : "Idea"} · {item.type}</p></article>)}</div>;
}

function EventChip({ item, timezone, color, selected, primary, onSelect }: { item: TravelObject; timezone: string; color: string; selected: boolean; primary: boolean; onSelect: (item: TravelObject, additive?: boolean) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: item.id, data: { item }, disabled: item.id.startsWith("draft:") });
  const time = item.isAllDay ? "All day" : item.startDateTime ? formatTripDate(item.startDateTime, timezone, { hour: "numeric", minute: "2-digit" }) : "Flexible";
  const style: CSSProperties = { backgroundColor: `${color}20`, borderColor: `${color}70`, color, ...(transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : {}) };
  return <button ref={setNodeRef} style={style} onClick={(event) => onSelect(item, event.shiftKey)} onDoubleClick={(event) => event.stopPropagation()} className={`group flex w-full items-start gap-1 rounded-md border px-1.5 py-1 text-left text-[11px] leading-tight shadow-sm hover:brightness-95 ${selectionRing(selected, primary)} ${isDragging ? "z-20 opacity-40" : ""}`} {...attributes} {...listeners}><GripVertical size={11} className="mt-0.5 shrink-0 opacity-40 group-hover:opacity-100" /><span className="min-w-0 flex-1 truncate font-medium">{item.title}</span><span className="hidden shrink-0 text-[10px] opacity-75 sm:inline">{time}</span></button>;
}

function DayCell({ date, currentMonth, items, timezone, typeColors, reservedRows, selectedIds, primarySelectedId, onSelect, onCreateItem }: { date: string; currentMonth: string; items: TravelObject[]; timezone: string; typeColors: Record<string, string>; reservedRows: number; selectedIds: ReadonlySet<string>; primarySelectedId: string | null; onSelect: (item: TravelObject, additive?: boolean) => void; onCreateItem: (date: string) => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: `day:${date}` }); const [, , day] = date.split("-").map(Number); const today = dateParts(new Date(), timezone).date;
  return <div ref={setNodeRef} onDoubleClick={() => onCreateItem(date)} title="Double-click to add an item" className={`min-h-[116px] border-b border-r p-1.5 transition-colors sm:min-h-[132px] ${date.slice(0, 7) === currentMonth ? "bg-white dark:bg-neutral-900" : "bg-stone-50/70 dark:bg-neutral-950"} ${isOver ? "bg-emerald-50 ring-2 ring-inset ring-emerald-400 dark:bg-emerald-950" : ""}`}><div className={`mb-1 flex h-6 w-6 items-center justify-center text-xs ${date === today ? "rounded-full bg-emerald-700 font-semibold text-white" : "text-stone-500 dark:text-stone-400"}`}>{day}</div><div className="space-y-1" style={{ paddingTop: `${reservedRows * 22}px` }}>{items.map((item) => <EventChip key={item.id} item={item} timezone={timezone} color={typeColor(item.type, typeColors)} selected={selectedIds.has(item.id)} primary={primarySelectedId === item.id} onSelect={onSelect} />)}</div></div>;
}

function MultiDayBar({ item, weekStart, startColumn, dayCount, lane, startsHere, endsHere, color, selected, primary, onSelect }: { item: TravelObject; weekStart: string; startColumn: number; dayCount: number; lane: number; startsHere: boolean; endsHere: boolean; color: string; selected: boolean; primary: boolean; onSelect: (item: TravelObject, additive?: boolean) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: `${item.id}:${weekStart}`, data: { item }, disabled: item.id.startsWith("draft:") });
  const style: CSSProperties = { left: `calc(${(startColumn / 7) * 100}% + 2px)`, width: `calc(${(dayCount / 7) * 100}% - 4px)`, top: `${29 + lane * 23}px`, backgroundColor: `${color}30`, borderColor: `${color}80`, color, ...(transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : {}) };
  return <button ref={setNodeRef} style={style} onClick={(event) => onSelect(item, event.shiftKey)} onDoubleClick={(event) => event.stopPropagation()} title={item.title} className={`absolute z-10 flex h-5 items-center gap-1 border px-1.5 text-left text-[10px] font-medium shadow-sm hover:brightness-95 ${startsHere ? "rounded-l-md" : "border-l-0"} ${endsHere ? "rounded-r-md" : "border-r-0"} ${selectionRing(selected, primary)} ${isDragging ? "opacity-40" : ""}`} {...attributes} {...listeners}><span className="truncate">{item.title}</span></button>;
}

function IdeaCard({ item, color, selected, primary, onSelect }: { item: TravelObject; color: string; selected: boolean; primary: boolean; onSelect: (item: TravelObject, additive?: boolean) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: item.id, data: { item } }); const place = item.location?.name ?? item.location?.address;
  return <button ref={setNodeRef} {...attributes} {...listeners} type="button" onClick={(event) => { event.stopPropagation(); onSelect(item, event.shiftKey); }} style={{ borderLeftColor: color, ...(transform ? { transform: `translate3d(${transform.x}px,${transform.y}px,0)` } : {}) }} className={`w-full rounded-lg border border-l-4 bg-background px-3 py-2.5 text-left shadow-sm ${selectionRing(selected, primary)} ${isDragging ? "opacity-40" : ""}`}><span className="block truncate text-xs font-semibold">{item.title}</span><span className="mt-1 block truncate text-[10px] text-muted-foreground">{place || item.type}</span></button>;
}

function IdeasPanel({ items, typeColors, selectedIds, primarySelectedId, onSelect, onAdd, onClose }: { items: TravelObject[]; typeColors: Record<string, string>; selectedIds: ReadonlySet<string>; primarySelectedId: string | null; onSelect: (item: TravelObject, additive?: boolean) => void; onAdd: () => void; onClose: () => void }) {
  const [query, setQuery] = useState(""); const { setNodeRef, isOver } = useDroppable({ id: "unscheduled" }); const filtered = items.filter((item) => `${item.title} ${item.type} ${item.location?.name ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <aside ref={setNodeRef} className={`absolute inset-y-0 left-0 z-40 flex w-[min(88vw,320px)] flex-col border-r bg-stone-50/95 shadow-xl backdrop-blur dark:bg-neutral-950/95 ${isOver ? "ring-2 ring-inset ring-emerald-500" : ""}`}><div className="flex items-start justify-between gap-2 border-b px-3 py-3"><div><p className="flex items-center gap-1.5 text-sm font-semibold"><Lightbulb size={14} /> Ideas <span className="rounded-full bg-stone-200 px-2 py-0.5 text-[10px] dark:bg-neutral-800">{items.length}</span></p><p className="mt-1 text-[10px] leading-snug text-muted-foreground">Created and imported items without a day</p></div><Button type="button" variant="ghost" size="icon-xs" onClick={onClose} aria-label="Close ideas"><X /></Button></div><label className="relative mx-3 mt-3"><Search size={13} className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ideas" className="h-8 w-full rounded-md border bg-background pl-8 pr-2 text-xs outline-none focus:border-emerald-600" /></label><div className="min-h-0 flex-1 space-y-2 overflow-y-auto p-3">{filtered.map((item) => <IdeaCard key={item.id} item={item} color={typeColor(item.type, typeColors)} selected={selectedIds.has(item.id)} primary={primarySelectedId === item.id} onSelect={onSelect} />)}{filtered.length === 0 && <p className="rounded-lg border border-dashed px-3 py-6 text-center text-xs text-muted-foreground">{items.length ? "No matching ideas" : "No ideas yet"}</p>}</div><div className="border-t p-3"><Button type="button" variant="outline" size="sm" className="w-full" onClick={onAdd}><Plus size={14} /> Create idea</Button><p className="mt-2 text-center text-[10px] text-muted-foreground">Drop here to remove an item from the itinerary</p></div></aside>;
}

function AgendaGap({ date, order, onCreate }: { date: string; order: number; onCreate: (date: string, order: number) => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: `day-list:${date}:${order}` });
  return <div ref={setNodeRef} className={`group flex h-9 w-full items-center gap-3 px-2 transition ${isOver ? "bg-emerald-50 dark:bg-emerald-950/30" : ""}`}><span className="w-20 shrink-0" /><span className={`h-px flex-1 border-t transition ${isOver ? "border-2 border-emerald-500" : "border-dotted border-transparent group-hover:border-stone-300 dark:group-hover:border-neutral-600"}`} /><button type="button" aria-label={`Add item at position ${order + 1}`} onClick={() => onCreate(date, order)} className={`flex min-h-8 items-center gap-1 text-[10px] font-medium transition ${isOver ? "text-emerald-700" : "text-transparent group-hover:text-stone-500 dark:group-hover:text-stone-400"}`}><Plus size={12} /> Add item</button></div>;
}

function AgendaCard({ item, number, color, selected, primary, onSelect }: { item: TravelObject; number: number; color: string; selected: boolean; primary: boolean; onSelect: (item: TravelObject, additive?: boolean) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: `agenda:${item.id}`, data: { item } }); const location = item.location?.name ?? item.location?.address; const fixed = Boolean(item.startTime && item.endTime && !item.isAllDay); const cost = item.cost?.amount != null ? `${item.cost.currency} ${item.cost.amount.toLocaleString()}` : null;
  return <div ref={setNodeRef} {...attributes} {...listeners} style={transform ? { transform: `translate3d(${transform.x}px,${transform.y}px,0)` } : undefined} className={`group relative flex items-stretch gap-3 ${isDragging ? "opacity-40" : ""}`}><span className={`relative z-10 w-20 shrink-0 pt-4 text-right ${fixed ? "text-sm font-semibold text-stone-600 dark:text-stone-300" : "text-[11px] text-stone-400"}`}>{fixed ? item.startTime : item.isAllDay ? "All day" : ""}</span>{fixed && <span aria-hidden className="absolute left-24 right-0 top-7 border-t border-stone-300/80 dark:border-neutral-700" />}<article style={{ borderLeftColor: fixed ? "#8b5cf6" : color }} className={`relative z-10 min-w-0 flex-1 overflow-hidden rounded-xl border border-l-4 bg-white shadow-sm transition hover:shadow-md dark:bg-neutral-900 ${selectionRing(selected, primary)}`}><div className="flex"><div className="flex w-14 shrink-0 items-start justify-center border-r bg-stone-50 px-1 py-4 dark:bg-neutral-800/60"><span className="grid size-7 place-items-center rounded-full text-xs font-bold text-white" style={{ backgroundColor: fixed ? "#8b5cf6" : color }}>{number}</span></div><button type="button" onClick={(event) => onSelect(item, event.shiftKey)} className="min-w-0 flex-1 px-4 py-3 text-left"><div className="flex items-start gap-2"><GripVertical size={15} className="mt-0.5 shrink-0 text-muted-foreground opacity-50 group-hover:opacity-100" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}{fixed && <span className="ml-2 text-[10px] font-medium text-violet-600 dark:text-violet-300">Fixed time</span>}</p><p className="mt-1 text-xs text-muted-foreground">{item.type}{cost ? ` · ${cost}` : ""}</p>{location && <p className="mt-2 flex items-center gap-1.5 truncate text-xs text-muted-foreground"><MapPin size={12} className="shrink-0" />{location}</p>}</div></div></button></div></article></div>;
}

function DayAgenda({ date, items, trip, typeColors, selectedIds, primarySelectedId, onSelect, onCreateItem }: { date: string; items: TravelObject[]; trip: Trip; typeColors: Record<string, string>; selectedIds: ReadonlySet<string>; primarySelectedId: string | null; onSelect: (item: TravelObject, additive?: boolean) => void; onCreateItem: (date: string, order: number) => void }) {
  const tripStart = trip.startDate.slice(0, 10); const tripEnd = trip.endDate.slice(0, 10); const isWithinTrip = date >= tripStart && date <= tripEnd; const dayIndex = Math.floor((Date.parse(`${date}T00:00:00Z`) - Date.parse(`${tripStart}T00:00:00Z`)) / 86400000) + 1; const dayItems = isWithinTrip ? items.filter((item) => itemAppearsOnDate(item, date, trip.timezone)) : []; const allDay = dayItems.filter((item) => item.isAllDay).sort(agendaSort); const agenda = dayItems.filter((item) => !item.isAllDay).sort(agendaSort); const { setNodeRef: setEmptyDropRef, isOver: isEmptyDropOver } = useDroppable({ id: `day-list:${date}:0` });
  return <div className="min-h-0 flex-1 overflow-y-auto bg-stone-50/60 dark:bg-neutral-950"><div className="mx-auto w-full max-w-3xl px-3 py-5 sm:px-7"><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-xs font-medium text-muted-foreground">{isWithinTrip ? `Day ${dayIndex}` : "Outside trip dates"}</p><h2 className="text-lg font-semibold">{formatTripDate(`${date}T12:00:00Z`, trip.timezone, { weekday: "long", month: "long", day: "numeric" })}</h2></div><div className="text-right"><p className="text-xs text-muted-foreground">{agenda.length + allDay.length} {agenda.length + allDay.length === 1 ? "item" : "items"}</p><p className="mt-1 text-[10px] text-muted-foreground">Open Day for the trip reader and map</p></div></div>{isWithinTrip ? <div>{allDay.length > 0 && <section className="mb-3 rounded-xl border bg-white p-3 dark:bg-neutral-900"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">All day</p><div className="space-y-2">{allDay.map((item, index) => <AgendaCard key={item.id} item={item} number={index + 1} color={typeColor(item.type, typeColors)} selected={selectedIds.has(item.id)} primary={primarySelectedId === item.id} onSelect={onSelect} />)}</div></section>}{agenda.map((item, index) => <div key={item.id}><AgendaGap date={date} order={allDay.length + index} onCreate={onCreateItem} /><AgendaCard item={item} number={allDay.length + index + 1} color={typeColor(item.type, typeColors)} selected={selectedIds.has(item.id)} primary={primarySelectedId === item.id} onSelect={onSelect} /></div>)}<AgendaGap date={date} order={allDay.length + agenda.length} onCreate={onCreateItem} />{agenda.length + allDay.length === 0 && <div ref={setEmptyDropRef} className={`grid min-h-48 place-items-center rounded-xl border border-dashed transition-colors ${isEmptyDropOver ? "border-emerald-500 bg-emerald-50 dark:bg-emerald-950/30" : ""}`}><div className="text-center"><p className="text-sm font-medium">Nothing planned yet</p><p className="mt-1 text-xs text-muted-foreground">Drag an idea onto this day or create an item.</p><Button type="button" variant="outline" size="sm" className="mt-3" onClick={() => onCreateItem(date, 0)}><Plus size={14} /> Add item</Button></div></div>}</div> : <div className="grid min-h-40 place-items-center rounded-xl border border-dashed px-5 text-center text-sm text-muted-foreground">This date is outside the trip.</div>}</div></div>;
}

function DayTab({ date, count, selected, timezone, onSelect }: { date: string; count: number; selected: boolean; timezone: string; onSelect: () => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: `day-list:${date}:${count}` }); const label = formatTripDate(`${date}T12:00:00Z`, timezone, { weekday: "short" }); const day = Number(date.slice(-2));
  return <button ref={setNodeRef} type="button" onClick={onSelect} aria-current={selected ? "date" : undefined} className={`min-w-0 rounded-lg border px-1 py-2 text-center transition ${selected ? "border-emerald-600 bg-emerald-50 dark:bg-emerald-950/40" : "border-transparent hover:bg-stone-100 dark:hover:bg-neutral-800"} ${isOver ? "ring-2 ring-emerald-500" : ""}`}><span className="block text-[10px] font-semibold uppercase text-muted-foreground">{label}</span><span className="mt-0.5 block text-sm font-semibold">{day}</span><span className="mt-0.5 block truncate text-[10px] text-muted-foreground">{count ? `${count} ${count === 1 ? "item" : "items"}` : "Empty"}</span></button>;
}

function WeekStrip({ dates, focusDate, items, trip, onSelect }: { dates: string[]; focusDate: string; items: TravelObject[]; trip: Trip; onSelect: (date: string) => void }) {
  return <div className="grid grid-cols-7 gap-1 border-b bg-white px-2 py-2 dark:bg-neutral-900 sm:gap-2 sm:px-4">{dates.map((date) => <DayTab key={date} date={date} count={items.filter((item) => itemAppearsOnDate(item, date, trip.timezone)).length} selected={date === focusDate} timezone={trip.timezone} onSelect={() => onSelect(date)} />)}</div>;
}

export function CalendarView({ trip, items, typeColors = {}, selectedIds, primarySelectedId, onSelect, onSelectForDrag, onMove, onUnschedule, onFlexibleDrop = async (item, date, order, clearTime, placementTime) => { await api.reorderObjects({ tripId: trip.id, objectId: item.id, date, dayOrder: order, clearTime, placementTime }); window.location.reload(); }, onCreateItem }: { trip: Trip; items: TravelObject[]; typeColors?: Record<string, string>; selectedIds: ReadonlySet<string>; primarySelectedId: string | null; onSelect: (item: TravelObject, additive?: boolean) => void; onSelectForDrag: (item: TravelObject) => void; onMove: (item: TravelObject, date: string, time?: string) => Promise<void>; onUnschedule: (item: TravelObject) => Promise<void>; onFlexibleDrop?: (item: TravelObject, date: string, order: number, clearTime: boolean, placementTime?: string) => Promise<void>; onCreateItem: (date?: string, time?: string, type?: string, title?: string, dayOrder?: number) => void }) {
  const start = trip.startDate.slice(0, 10); const tripEnd = trip.endDate.slice(0, 10); const mode = useTravelStore((state) => state.calendarMode); const setMode = useTravelStore((state) => state.setCalendarMode); const selectedAtMount = primarySelectedId ? items.find((item) => item.id === primarySelectedId) : null; const selectedDateAtMount = selectedAtMount ? itemDates(selectedAtMount, trip.timezone).first : null; const initialDate = selectedDateAtMount && selectedDateAtMount >= start && selectedDateAtMount <= tripEnd ? selectedDateAtMount : start; const [focusDate, setFocusDate] = useState(initialDate); const [dayScrollRequest, setDayScrollRequest] = useState({ date: initialDate, nonce: 0 }); const [activeItem, setActiveItem] = useState<TravelObject | null>(null); const [ideasOpen, setIdeasOpen] = useState(false); const suppressClickRef = useRef(false); const previousModeRef = useRef<Mode>(mode); const today = dateParts(new Date(), trip.timezone).date; const month = useMemo(() => { const date = new Date(`${focusDate}T00:00:00Z`); return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1)); }, [focusDate]); const grid = useMemo(() => monthGrid(month), [month]); const currentMonth = month.toISOString().slice(0, 7); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 3 } })); const ideas = items.filter((item) => item.date === null); const scheduledItems = items.filter((item) => item.date !== null);
  const spans = scheduledItems.map((item) => { const { first, last } = itemDates(item, trip.timezone); return { item, start: first!, end: last ?? first! }; }).filter(({ item, start: spanStart, end }) => Boolean(spanStart && end && (end > spanStart || item.isAllDay))); const byDay = new Map<string, TravelObject[]>(); for (const item of scheduledItems) { const { first } = itemDates(item, trip.timezone); if (first && !spans.some((span) => span.item.id === item.id)) byDay.set(first, [...(byDay.get(first) ?? []), item]); }
  const weeks = Array.from({ length: 6 }, (_, index) => grid.slice(index * 7, index * 7 + 7)); const weekSegments = weeks.map((days) => { const segments = spans.filter(({ start: spanStart, end }) => spanStart <= days[6] && end >= days[0]).map(({ item, start: spanStart, end }) => { const segmentStart = spanStart < days[0] ? days[0] : spanStart; const segmentEnd = end > days[6] ? days[6] : end; const startColumn = days.indexOf(segmentStart); const endColumn = days.indexOf(segmentEnd); return { item, start: segmentStart, end: segmentEnd, startColumn, dayCount: endColumn - startColumn + 1, startsHere: spanStart >= days[0], endsHere: end <= days[6] }; }).sort((a, b) => Number(b.item.isAllDay) - Number(a.item.isAllDay) || a.startColumn - b.startColumn || b.dayCount - a.dayCount); const laneEnds: string[] = []; const placed = segments.map((segment) => { let lane = laneEnds.findIndex((end) => end < segment.start); if (lane < 0) lane = laneEnds.length; laneEnds[lane] = segment.end; return { ...segment, lane }; }); return { days, segments: placed, laneCount: laneEnds.length }; }); const weekStart = sundayOf(focusDate); const weekDates = Array.from({ length: 7 }, (_, index) => shiftDate(weekStart, index));
  const requestDay = useCallback((date: string) => { const bounded = date < start ? start : date > tripEnd ? tripEnd : date; setFocusDate(bounded); setDayScrollRequest((request) => ({ date: bounded, nonce: request.nonce + 1 })); }, [start, tripEnd]);
  useEffect(() => { const changedMode = previousModeRef.current !== mode; previousModeRef.current = mode; if (!changedMode || mode === "month" || !primarySelectedId) return; const selected = items.find((item) => item.id === primarySelectedId); const selectedDate = selected ? itemDates(selected, trip.timezone).first : null; if (!selectedDate) return; const frame = requestAnimationFrame(() => { if (mode === "day") requestDay(selectedDate); else setFocusDate(selectedDate); }); return () => cancelAnimationFrame(frame); }, [items, mode, primarySelectedId, requestDay, trip.timezone]);
  useEffect(() => { function onKeyDown(event: KeyboardEvent) { if (event.defaultPrevented || event.altKey || event.ctrlKey || event.metaKey) return; const target = event.target; if (target instanceof HTMLElement && (target.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName))) return; if (event.code === "Space" && mode !== "month") { event.preventDefault(); setIdeasOpen((open) => !open); return; } const direction = event.key === "ArrowRight" || event.key === "ArrowDown" ? 1 : event.key === "ArrowLeft" || event.key === "ArrowUp" ? -1 : 0; if (!direction || mode === "month") return; event.preventDefault(); if (mode === "day") requestDay(shiftDate(focusDate, direction)); else setFocusDate((date) => shiftDate(date, direction)); } window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [focusDate, mode, requestDay]);
  function finishDrag() { setActiveItem(null); requestAnimationFrame(() => { suppressClickRef.current = false; }); }
  function handleDragStart(event: DragStartEvent) { suppressClickRef.current = true; const item = (event.active.data.current as { item?: TravelObject } | undefined)?.item ?? items.find((candidate) => candidate.id === String(event.active.id).split(":").at(-1)); setActiveItem(item ?? null); if (item && !selectedIds.has(item.id)) onSelectForDrag(item); }
  async function handleDragEnd(event: DragEndEvent) { finishDrag(); const target = String(event.over?.id ?? ""); const item = (event.active.data.current as { item?: TravelObject } | undefined)?.item; if (!item) return; if (target === "unscheduled") { if (item.date !== null) await onUnschedule(item); return; } if (target.startsWith("day-list:")) { const [, date, rawOrder] = target.split(":"); if (date) { await onFlexibleDrop(item, date, Number(rawOrder) || 0, false); setFocusDate(date); } return; } if (target.startsWith("day:")) await onMove(item, target.slice(4)); }
  function selectFromClick(item: TravelObject, additive = false) { if (!suppressClickRef.current) onSelect(item, additive); }
  function navigate(direction: number) { if (mode === "month") { const date = new Date(`${focusDate}T00:00:00Z`); date.setUTCMonth(date.getUTCMonth() + direction); setFocusDate(date.toISOString().slice(0, 10)); } else if (mode === "week") setFocusDate(shiftDate(focusDate, direction * 7)); else requestDay(shiftDate(focusDate, direction)); }
  function goToToday() { setMode("day"); requestDay(today >= start && today <= tripEnd ? today : start); }
  const activeDragItems = activeItem ? [activeItem, ...items.filter((item) => item.id !== activeItem.id && selectedIds.has(item.id))] : [];
  const title = mode === "month" ? new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric", timeZone: "UTC" }).format(month) : mode === "week" ? `${formatTripDate(`${weekDates[0]}T12:00:00Z`, trip.timezone, { month: "short", day: "numeric" })} – ${formatTripDate(`${weekDates[6]}T12:00:00Z`, trip.timezone, { month: "short", day: "numeric", year: "numeric" })}` : `${formatTripDate(`${start}T12:00:00Z`, trip.timezone, { month: "short", day: "numeric" })} – ${formatTripDate(`${tripEnd}T12:00:00Z`, trip.timezone, { month: "short", day: "numeric", year: "numeric" })}`;
  return <div className="relative flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border bg-white shadow-sm dark:bg-neutral-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3"><div><p className="text-sm font-semibold">{title}</p><p className="mt-0.5 text-xs text-muted-foreground">{mode === "week" ? "Choose a day, then arrange its visit order" : mode === "day" ? "Continuous itinerary · map follows the active day" : `Times shown in ${trip.timezone}`}</p></div><div className="flex items-center gap-2">{mode !== "month" && <><Button variant={ideasOpen ? "secondary" : "outline"} size="sm" onClick={() => setIdeasOpen((open) => !open)}><Lightbulb size={14} /> Ideas <span className="rounded-full bg-background/70 px-1.5 text-[10px]">{ideas.length}</span></Button><Button variant="outline" size="sm" onClick={() => onCreateItem()}><Plus size={14} /> Add idea</Button></>}<div className="flex rounded-lg border p-0.5">{(["month", "week", "day"] as Mode[]).map((view) => <Button key={view} variant={mode === view ? "secondary" : "ghost"} size="sm" className="capitalize" onClick={() => { setMode(view); if (view === "day") requestDay(focusDate); }}>{view}<kbd className="ml-1 rounded border px-1 text-[9px] font-normal opacity-60">{view === "month" ? "Q" : view === "week" ? "W" : "E"}</kbd></Button>)}</div><Button variant="ghost" size="icon-sm" onClick={() => navigate(-1)} aria-label="Previous period"><ChevronLeft /></Button><Button variant="outline" size="sm" onClick={goToToday}>Today</Button><Button variant="outline" size="sm" onClick={() => mode === "day" ? requestDay(start) : setFocusDate(start)}>Trip start</Button><Button variant="ghost" size="icon-sm" onClick={() => navigate(1)} aria-label="Next period"><ChevronRight /></Button></div></div>
    {mode === "month" ? <DndContext sensors={sensors} onDragStart={handleDragStart} onDragCancel={finishDrag} onDragEnd={(event) => { void handleDragEnd(event); }}><div className="grid grid-cols-7 border-b bg-stone-50 text-center text-[10px] font-semibold uppercase tracking-wider text-stone-500 dark:bg-neutral-800 dark:text-stone-300 sm:text-xs">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <div key={day} className="py-2">{day}</div>)}</div><div className="min-h-0 flex-1 overflow-y-auto">{weekSegments.map(({ days, segments, laneCount }) => <div key={days[0]} className="relative grid grid-cols-7">{days.map((date) => <DayCell key={date} date={date} currentMonth={currentMonth} items={(byDay.get(date) ?? []).sort(agendaSort)} timezone={trip.timezone} typeColors={typeColors} reservedRows={laneCount} selectedIds={selectedIds} primarySelectedId={primarySelectedId} onSelect={selectFromClick} onCreateItem={onCreateItem} />)}{segments.map((segment) => <MultiDayBar key={`${segment.item.id}:${days[0]}`} item={segment.item} weekStart={days[0]} startColumn={segment.startColumn} dayCount={segment.dayCount} lane={segment.lane} startsHere={segment.startsHere} endsHere={segment.endsHere} color={typeColor(segment.item.type, typeColors)} selected={selectedIds.has(segment.item.id)} primary={primarySelectedId === segment.item.id} onSelect={selectFromClick} />)}</div>)}</div><DragOverlay dropAnimation={null}>{activeDragItems.length ? <CalendarDragPreview items={activeDragItems} timezone={trip.timezone} typeColors={typeColors} /> : null}</DragOverlay></DndContext> : <DndContext sensors={sensors} onDragStart={handleDragStart} onDragCancel={finishDrag} onDragEnd={(event) => { void handleDragEnd(event); }}><div className="relative flex min-h-0 flex-1 flex-col">{ideasOpen && <IdeasPanel items={ideas} typeColors={typeColors} selectedIds={selectedIds} primarySelectedId={primarySelectedId} onSelect={selectFromClick} onAdd={() => onCreateItem()} onClose={() => setIdeasOpen(false)} />}{mode === "week" && <WeekStrip dates={weekDates} focusDate={focusDate} items={scheduledItems} trip={trip} onSelect={setFocusDate} />}{mode === "week" ? <DayAgenda date={focusDate} items={scheduledItems} trip={trip} typeColors={typeColors} selectedIds={selectedIds} primarySelectedId={primarySelectedId} onSelect={selectFromClick} onCreateItem={(date, order) => onCreateItem(date, undefined, undefined, "(untitled event)", order)} /> : <DayJourneyView trip={trip} items={scheduledItems} typeColors={typeColors} selectedIds={selectedIds} primarySelectedId={primarySelectedId} scrollRequest={dayScrollRequest} onActiveDate={setFocusDate} onSelect={selectFromClick} onCreateItem={(date, order) => onCreateItem(date, undefined, undefined, "(untitled event)", order)} />}</div><DragOverlay dropAnimation={null}>{activeDragItems.length ? <CalendarDragPreview items={activeDragItems} timezone={trip.timezone} typeColors={typeColors} /> : null}</DragOverlay></DndContext>}
    <div className="flex items-center gap-2 border-t px-4 py-2 text-xs text-muted-foreground"><Clock size={13} />{mode === "month" ? "Drag items to another date. Double-click a date to add an item." : mode === "week" ? "Drag an idea onto a day, then drop it into the exact visit-order gap." : "Scroll the whole trip; the map follows the active day. Drag cards into exact order gaps."}{mode !== "month" && <span className="ml-auto">Press <kbd className="rounded border bg-stone-100 px-1.5 py-0.5 font-mono text-[10px] dark:bg-neutral-800">Space</kbd> to toggle Ideas</span>}</div></div>;
}
